// <auto-generated />
// ========================================
// 自动生成的UI绑定代码
// 源文件: Assets/Game/Resources/UI/GameUI.prefab
// 生成时间: 2025-10-26 13:48:27
// 警告: 请勿手动修改此文件，所有修改将在重新生成时丢失
// ========================================

using UnityEngine;
using UnityEngine.UI;
using Framework.Core;

namespace Game.UI
{
    /// <summary>
    /// GameUI - 自动生成的组件绑定
    /// </summary>
    public partial class GameUI : UIBehaviour
    {
        #region Auto-Generated Fields
        
        /// <summary>
        /// Start
        /// 路径: GameUI/Panel/@Button_Start
        /// </summary>
        private Button _startButton;
        
        /// <summary>
        /// Settings
        /// 路径: GameUI/Panel/@Button_Settings
        /// </summary>
        private Button _settingsButton;
        
        /// <summary>
        /// Title
        /// 路径: GameUI/Panel/@Text_Title
        /// </summary>
        private Text _titleText;
        
        #endregion
        
        #region Auto-Generated Binding
        
        /// <summary>
        /// 绑定所有标记的组件
        /// 路径记录在生成时，精确查找
        /// </summary>
        protected override void BindComponents()
        {
            base.BindComponents();
            
            // 注意：路径是相对于当前GameObject的，不包含根节点名称
            _startButton = FindComponent<Button>("Panel/@Button_Start");
            _settingsButton = FindComponent<Button>("Panel/@Button_Settings");
            _titleText = FindComponent<Text>("Panel/@Text_Title");
        }
        
        #endregion
        
        #region Auto-Generated Events
        
        /// <summary>
        /// 注册所有Button事件
        /// </summary>
        protected override void RegisterEvents()
        {
            base.RegisterEvents();
            
            _startButton.onClick.AddListener(OnStartClick);
            _settingsButton.onClick.AddListener(OnSettingsClick);
        }
        
        /// <summary>
        /// 注销所有Button事件
        /// </summary>
        protected override void UnregisterEvents()
        {
            // 添加空检查，防止组件未找到时出错
            if (_startButton != null)
                _startButton.onClick.RemoveListener(OnStartClick);
            if (_settingsButton != null)
                _settingsButton.onClick.RemoveListener(OnSettingsClick);
            
            base.UnregisterEvents();
        }
        
        #endregion
    }
}
